config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :users do
    collection do
      get 'teacher', default: {role: 'teacher'}
      get 'parent_register', default: {role: 'teacher'}
    end
  end
  get '/voices', to: 'voices#index'
  post '/call', to: 'voices#call', as: 'call'
  get '/calling', to: 'voices#calling'
  post '/connect/:sales_number', to: 'voices#connect', as: 'connect'

  get '/search', to: 'welcome#search'
  get '/psychologists', to: 'welcome#psychologists'
  get '/chat', to: 'welcome#chat'
  get '/calendar', to: 'welcome#calendar'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, inverse_of: :bookings
  belongs_to :psychologist, inverse_of: :bookings
end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  attr_accessor :user_phone
  attr_accessor :sales_phone
  validates_presence_of :user_phone
  validates_presence_of :sales_phone

  def encoded_sales_phone
    URI.encode(sales_phone)
  end
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/psychologist.rb
class Psychologist < ApplicationRecord
  has_many :bookings, inverse_of: :psycologist, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, inverse_of: :user, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/search'
    end
  end

  def register
    @user = User.new(role: params[:role])
    render 'register'
  end

  alias_method :teacher, :register
  alias_method :parent_register, :register


  private
  def user_params
    params.require(:user).permit(:age, :emotional_problem, :symptom, :other_info, :role)
  end
end

app/controllers/voices_controller.rb
require 'twilio-ruby'

class VoicesController < ApplicationController
  # Before we allow the incoming request to connect, verify
  # that it is a Twilio request
  before_action :load_credentials, only: [:call, :connect]
  before_action :authenticate_twilio_request, only: [:connect]
  skip_before_action :verify_authenticity_token, only: [:connect]

  # Render home page
  def index
    @contact =Contact.new
    render 'index'
  end

  def call
    contact = Contact.new
    contact.sales_phone = '514-248-8681'
    contact.user_phone =  contact_params[:user_phone]

    # Validate contact
    if contact.valid?
      @client = Twilio::REST::Client.new @twilio_sid, @twilio_token
      # Connect an outbound call to the number submitted
      @call = @client.calls.create(
          to: contact.user_phone,
          from: @twilio_number,
          url: "#{@api_host}/connect/#{contact.encoded_sales_phone}" # Fetch instructions from this URL when the call connects
      )
      @msg = { message: 'Phone call incoming!', status: 'ok' }
    else
      @msg = { message: contact.errors.full_messages, status: 'ok' }
    end

    respond_to do |format|
      format.html { redirect_to '/calling' }
      format.json { render json: @msg }
    end
  end

  def connect
    response = Twilio::TwiML::VoiceResponse.new do |r|
      r.say('Thanks for using our home room services.
             We are connecting to home room psychologist', voice: 'alice')
      r.dial do |dial|
        dial.number('514-248-8681')
      end
    end


    render xml: response.to_s
  end

  private

  def authenticate_twilio_request
    if twilio_req?
      return true
    else
      response = Twilio::TwiML::VoiceResponse.new do |r|
        r.hangup
      end

      render xml: response.to_s, status: :unauthorized
      false
    end
  end

  def twilio_req?
    # Helper from twilio-ruby to validate requests.
    validator = Twilio::Security::RequestValidator.new(@twilio_token)

    post_vars = params.reject { |k, _| k.downcase == k }
    twilio_signature = request.headers['HTTP_X_TWILIO_SIGNATURE']

    validator.validate(request.url, post_vars, twilio_signature)
  end

  def load_credentials
    @twilio_sid = 'askjdklsajdlksajdkls'
    @twilio_token = 'dasdksalkdjlasklasjdl'
    @twilio_number = '+29381293'
    @api_host = 'http://65ab6379.ngrok.io'
  end

  def contact_params
    params.require(:contact).permit(:user_phone)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def teacher

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def symptoms1
    {
        anxiety: 'Anxiety',
        addiction: 'Addiction',
        depression: 'Depression'
    }
  end

  def symptoms2
    {
        stress: 'Stress',
        'self-esteem': 'Self-Esteem',
        relationships: 'Relationships'
    }
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def list_questions
    {
        emotional_problem: "What's your emotional problem?",
        age: "How old are you?",
        symptom: "What's the name of your school?",
        other_info: "Any other infomation?"
    }
  end
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'shared/head' %>

<body>

<%= yield %>

</body>
</html>

app/views/shared/_banner.html.erb
<header class="ms-hero-page ms-hero-img-keyboard ms-hero-bg-dark color-white ms-navbar-white">
  <div class="container index-1">
    <div class="row">
      <div class="col-lg-6">
        <h1 class="text-uppercase animated fadeInDown animation-delay-5 typed-title">It's time for
          <br>
          <span class="color-primary typed-class">better help.</span>
        </h1>
        <p class="lead lead-sm animated fadeInLeft animation-delay-7 color-light">Fugit velit necessitatibus maiores ex
          sit modi vitae repellendus, doloremque optio libero voluptas sed suscipit officiis ducimus iste.</p>
        <ul class="ms-list-arrow">
          <li class="animated fadeInUp animation-delay-7">Convenient</li>
          <li class="animated fadeInUp animation-delay-10">Affordable</li>
          <li class="animated fadeInUp animation-delay-13">Private online counseling</li>
          <li class="animated fadeInUp animation-delay-16">Anytime, anywhere.</li>
        </ul>
        <div class="text-center">
          <%= link_to teacher_users_path, class: 'btn btn-raised btn-lg btn-white
              color-primary animated flipInX animation-delay-20' do %>
            <i class="zmdi zmdi-graduation-cap"></i> I am teacher
          <% end %>
          <%= link_to parent_register_users_path, class: 'btn btn-raised btn-lg btn-warning animated flipInX animation-delay-24' do %>
            <i class="zmdi zmdi-male-female"></i> I am parent
          <% end %>
        </div>
      </div>
      <div class="col-lg-6 text-center mt-4">

        <%= image_tag('kindness-classroom-web.jpg', class: 'img-fluid animated zoomInDown animation-delay-3 index-1') %>

      </div>
      <div class="col-lg-12">
        <div class="text-center ms-margin">
          <a href="javascript:void(0)" class="btn btn-primary btn-raised btn-app wow flipInX animation-delay-20">
            <div class="btn-container">
              <i class="fa fa-html5"></i>
              <span>Aviable as</span>
              <br>
              <strong>Web App</strong>
            </div>
          </a>
          <a href="javascript:void(0)" class="btn btn-primary btn-raised btn-app wow flipInX animation-delay-22">
            <div class="btn-container">
              <i class="fa fa-windows"></i>
              <span>Download for</span>
              <br>
              <strong>Windows</strong>
            </div>
          </a>
          <a href="javascript:void(0)" class="btn btn-primary btn-raised btn-app wow flipInX animation-delay-24">
            <div class="btn-container">
              <i class="fa fa-apple"></i>
              <span>Download for</span>
              <br>
              <strong>MacOS</strong>
            </div>
          </a>
          <a href="javascript:void(0)" class="btn btn-primary btn-raised btn-app wow flipInX animation-delay-26">
            <div class="btn-container">
              <i class="fa fa-android"></i>
              <span>Aviable in </span>
              <br>
              <strong>Play Store</strong>
            </div>
          </a>
          <a href="javascript:void(0)" class="btn btn-primary btn-raised btn-app wow flipInX animation-delay-28">
            <div class="btn-container">
              <i class="fa fa-apple"></i>
              <span>Aviable in </span>
              <br>
              <strong>App Store</strong>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_head.html.erb
<head>
  <title>Homeroom</title>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="<%=image_path('homeroom_icon.png')%>">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application.css', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</head>

app/views/shared/_header.html.erb
<header class="ms-header ms-header-primary">
  <!--ms-header-primary-->
  <div class="container container-full">
    <div class="ms-title">
      <a href="/">
        <!-- <img src="assets/img/demo/logo-header.png" alt=""> -->
        <span class="ms-logo animated zoomInDown animation-delay-5">H</span>
        <h1 class="animated fadeInRight animation-delay-6">Home
          <span>Room</span>
        </h1>
      </a>
    </div>
    <div class="header-right">
      <div class="share-menu">
        <ul class="share-menu-list">
          <li class="animated fadeInRight animation-delay-3">
            <a href="javascript:void(0)" class="btn-circle btn-google">
              <i class="zmdi zmdi-google"></i>
            </a>
          </li>
          <li class="animated fadeInRight animation-delay-2">
            <a href="javascript:void(0)" class="btn-circle btn-facebook">
              <i class="zmdi zmdi-facebook"></i>
            </a>
          </li>
          <li class="animated fadeInRight animation-delay-1">
            <a href="javascript:void(0)" class="btn-circle btn-twitter">
              <i class="zmdi zmdi-twitter"></i>
            </a>
          </li>
        </ul>
        <a href="javascript:void(0)" class="btn-circle btn-circle-primary animated zoomInDown animation-delay-7">
          <i class="zmdi zmdi-share"></i>
        </a>
      </div>
      <form class="search-form animated zoomInDown animation-delay-9">
        <input id="search-box" type="text" class="search-input" placeholder="Search..." name="q" />
        <label for="search-box">
          <i class="zmdi zmdi-search"></i>
        </label>
      </form>
      <%= link_to teacher_users_path, class: 'btn btn-raised btn-lg btn-white
              color-primary animated flipInX animation-delay-20' do %>
        <i class="zmdi zmdi-graduation-cap"></i> I AM A TEACHER
      <% end %>
      <%= link_to parent_register_users_path, class: 'btn btn-raised btn-lg btn-warning animated flipInX animation-delay-24' do %>
        <i class="zmdi zmdi-male-female"></i> I AM A PARENT
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_top_nav.html.erb
<div class="container container-full">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">
      <!-- <img src="assets/img/demo/logo-navbar.png" alt=""> -->
      <span class="ms-logo ms-logo-sm">H</span>
      <span class="ms-title">Home
                <strong>Room</strong>
              </span>
    </a>
  </div>
  <div class="collapse navbar-collapse" id="ms-navbar">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a href="/" class="nav-link dropdown-toggle animated fadeIn animation-delay-7">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a href="/search" class="nav-link dropdown-toggle animated fadeIn animation-delay-7">Advices</a>
      </li>
      <li class="nav-item dropdown dropdown-megamenu-container">
        <a href="#" class="nav-link dropdown-toggle animated fadeIn animation-delay-7">FAQ</a>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle animated fadeIn animation-delay-7">Review</a>
      </li>
      <li class="nav-item dropdown">
        <a href="/psychologists" class="nav-link dropdown-toggle animated fadeIn animation-delay-8">Psychologists</a>
      </li>
    </ul>
  </div>
  <a href="javascript:void(0)" class="ms-toggle-left btn-navbar-menu">
    <i class="zmdi zmdi-menu"></i>
  </a>
</div>
<!-- container -->

app/views/shared/groups/_group.html.haml
.row
  - symptoms1.each do |sym, name|
    .col-md-4
      .card.mb-4{class: "card-#{cycle('primary', 'royal', 'warning')}"}
        .card-header
          %h2
            %i.zmdi.zmdi-group-work
            = name
        .withripple.zoom-img
          %a{href: '#'}
            =image_tag("symptom/#{sym}.jpg", class: 'img-fluid')
        .card-block
          .group-members
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--48px thumbnail--circle thumbnail-card')
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--24px thumbnail--circle thumbnail-card')
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--24px thumbnail--circle thumbnail-card')
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--24px thumbnail--circle thumbnail-card')
            %a{:href => "#"}
              %i.zmdi.zmdi-more
            %a.pull-right.btn.btn-primary.btn-xs.btn-raised{:href => "/chat"}
              %i.zmdi.zmdi-collection-plus
              Join
          %hr/
          .text-center
            .row
              .col
                %a.label-primary.label 1,200 members
              .col
                %a.label-info.label 500 active posts
.row
  - symptoms2.each do |sym, name|
    .col-md-4
      .card.mb-4{class: "card-#{cycle('primary', 'royal', 'warning')}"}
        .card-header
          %h2
            %i.zmdi.zmdi-group-work
            = name
        .withripple.zoom-img
          %a{href: '#'}
            =image_tag("symptom/#{sym}.jpg", class: 'img-fluid')

        .card-block
          .group-members
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--48px thumbnail--circle thumbnail-card')
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--24px thumbnail--circle thumbnail-card')
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--24px thumbnail--circle thumbnail-card')
            %a{:href => "#"}= image_tag('demo/avatar50.jpg', class: 'thumbnail--24px thumbnail--circle thumbnail-card')
            %a{:href => "#"}
              %i.zmdi.zmdi-more
            %a.pull-right.btn.btn-primary.btn-xs.btn-raised{:href => "/chat"}
              %i.zmdi.zmdi-collection-plus
              Join
          %hr/
          .text-center
            .row
              .col
                %a.label-primary.label 1,200 members
              .col
                %a.label-info.label 500 active posts

app/views/shared/posts/_post.html.haml
%article.card.wow.fadeInLeft.animation-delay-5.mb-4
  .card-block
    .row
      .col-lg-6
        = image_tag('demo/port6.jpg', class: 'img-responsive mb-4')
      .col-lg-6
        %h3.no-mt
          %a{:href => "javascript:void(0)"} Earum delectus libero ipsa temporibus in minus
        %p.mb-4 Lorem ipsum dolor sit amet, consectetur alter adipisicing elit. Facilis,
    .row
      .col-lg-8
        = image_tag('demo/avatar50.jpg', class: 'img-circle mr-1')
        by
        %a{:href => "javascript:void(0)"} Victoria
        in
        %a.ms-tag.ms-tag-info{:href => "javascript:void(0)"} Design
        %span.ml-1.hidden-xs
          %i.zmdi.zmdi-time.mr-05.color-info
          %span.color-medium-dark 3 days ago
      .col-lg-4.text-right
        %a.btn.btn-primary.btn-raised.btn-block.animate-icon{:href => "javascript:void(0)"}
          Read More
          %i.ml-1.no-mr.zmdi.zmdi-long-arrow-right

app/views/shared/questions/_question.html.haml
.card
  .topic-entry.clearfix
    .topic-entry__vote_container
      .topic-entry__vote
        %a{href: '#'}
          %i.zmdi.zmdi-chevron-up.ms-icon-2x
        .vote-number
          = rand(100)
        %a{href:'#'}
          %i.zmdi.zmdi-chevron-down.ms-icon-2x
    .topic-entry__block
      %h4.mt0.pt0
        %a{href: '#'}
          [Lorem Ipsum] Phasellus ullamcorper rhoncus sagittis.
      %small.text-muted
        In ac turpis vitae ante pretium cursus. Suspendisse nisl arcu, venenatis elementum lacinia sed.
        %br/
        %span.label.label-inverse 3 hours ago
        by
        %strong.color-primary @RobDoan
      %span.pull-right
        %i.zmdi.zmdi-comment-alt-text
        20 answers

app/views/shared/users/_user.html.erb
<% 2.times do %>
  <div class="row">
    <% 3.times do %>
      <div class="col-lg-4 col-md-6">
        <div class="card card-primary wow zoomInUp mb-2">
          <div class="withripple zoom-img">
            <a href="javascript:void()" class="">
              <%= image_tag("demo/doctors/p#{cycle(0, 1)}.jpg", class: 'img-fluid') %>
            </a>
          </div>
          <div class="card-block">
            <span class="label label-royal pull-right">Psychologist</span>
            <h3 class="color-royal">Dr. Giuseppe Alfonsi</h3>
            <p>
              Years in Practice: <b>8 Years</b>
              <br />
              School: <b>Université de Sherbrooke</b><br />
              License No. and State: <b>12912-16 Quebec</b>
            </p>
            <div class="row">
              <div class="col">
                <a href="javascript:void(0)" class="btn-circle btn-circle-raised btn-circle-xs mt-1 mr-1 no-mr-md btn-twitter">
                  <i class="zmdi zmdi-twitter"></i>
                </a>
                <a href="javascript:void(0)" class="btn-circle btn-circle-raised btn-circle-xs mt-1 mr-1 no-mr-md btn-linkedin">
                  <i class="zmdi zmdi-linkedin"></i>
                </a>
              </div>
              <div class="col text-right">
                <a href="/calendar" class="btn-circle btn-circle-raised btn-circle-xs mt-1 mr-1 no-mr-md btn-pinterest">
                  <i class="zmdi zmdi-calendar"></i>
                </a>

                <a href="/calendar" class="btn-circle btn-circle-raised btn-circle-xs mt-1 mr-1 no-mr-md btn-vine">
                  <i class="zmdi zmdi-phone"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/register.html.erb
<div class="ms-site-container ms-nav-fixed">
  <nav class="navbar navbar-expand-md navbar-fixed ms-lead-navbar navbar-mode navbar-mode mb-0" id="navbar-lead">
    <%= render 'shared/top_nav' %>
  </nav>
  <div class="wrap ms-hero-img-brain-color ms-hero-bg-info color-white ms-bg-fixed full-screen-height">
    <div class="intro-full-content index-1">
      <div class="container question-list">
        <div class="text-center mb-2">
          <%= form_for @user, class: 'form-horizontal'  do |f| %>
            <% i = 0 %>
            <% list_questions.each do |method, question| %>
              <% i += 1 %>
              <div class="question" data-question='<%= i %>' style="<%= 'display: none;' if i >= 2 %>">
                <h2 class="no-m color-white center-block mb-1 animated slideInDown">
                  <%= question %>
                </h2>
                <p class="lead lead-lg color-white text-center center-block mw-800 text-uppercase fw-300 animated fadeInUp animation-delay-2">
                  <%= f.text_field method, class: 'form-control' %>
                </p>
              </div>
            <% end %>
            <%= f.hidden_field :role %>
            <div class="text-center mb-2 d-none finish-cover">
              <buton class="btn btn-xlg btn-raised" id='submit-by-javascript'>
                <i class="zmdi zmdi-face"></i> Submit!
              </buton>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/voices/calling.html.erb
<div class="ms-site-container ms-nav-fixed">
  <nav class="navbar navbar-expand-md ms-lead-navbar navbar-mode navbar-mode mb-0" id="navbar-lead">
    <%= render 'shared/top_nav' %>
  </nav>
  <div class="wrap ms-hero-img-brain-color ms-hero-bg-info ms-bg-fixed full-screen-height">
    <div class="container text-center mt-6">
      &lt;<h1 class="no-m ms-site-title color-white center-block ms-site-title-lg mt-2 animated zoomInDown animation-delay-5">Connecting.......</h1>
      <p class="lead lead-lg color-white text-center center-block mt-2 mw-800 fw-300 animated fadeInUp animation-delay-7">
        We are connecting you with our psychologist
      </p>
    </div>
  </div>
</div>

app/views/voices/index.html.erb
<div class="ms-site-container">
  <nav class="navbar navbar-expand-md navbar-fixed ms-lead-navbar navbar-mode navbar-mode mb-0" id="navbar-lead">
    <%= render 'shared/top_nav' %>
  </nav>
  <div class="wrap ms-hero-img-brain-color ms-hero-bg-info color-white ms-bg-fixed full-screen-height">
    <div class="intro-full-content index-1">
      <div class="container">
        <div class="card animated card-primary fadeInUp animation-delay-2">
          <div class="card-header">
            <h3 class="card-title">Your contact info</h3>
          </div>
          <div class="card-block">
            <%= form_for :contact, url: '/call', method: :post do |f| %>
              <fieldset class="container">
                <div class="form-group row is-empty">
                  <%= f.label :user_phone, 'Phone Number', class: 'col-lg-2 control-label' %>
                  <div class="col-lg-9">
                    <%= f.text_field :user_phone, class: 'form-control', placeholder: '514-248-8681' %>
                  </div>
                </div>
                <div class="form-group row is-empty">
                  <label for="textArea" class="col-lg-2 control-label">Message</label>
                  <div class="col-lg-9">
                    <textarea class="form-control" rows="3" id="textArea" placeholder="Your message..."></textarea>
                  </div>
                </div>
                <div class="form-group row justify-content-end">
                  <div class="col-lg-10">
                    <button type="submit" class="btn btn-raised btn-primary">Submit</button>
                  </div>
                </div>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_category_filter.html.haml
/ Nav tabs
%ul.nav-tabs-full.shadow-2dp.nav.nav-tabs{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a.withoutripple{"aria-controls" => "home", "data-toggle" => "tab", :href => "#users", :role => "tab"}
      %i.zmdi.zmdi-accounts
      %span.hidden-xs Peoples
      %span.badge.badge-round.badge-danger 5
  %li{:role => "presentation"}
    %a.withoutripple{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#posts", :role => "tab"}
      %i.zmdi.zmdi-collection-text
      %span.hidden-xs Posts
      %span.badge.badge-round.badge-warning 3
  %li{:role => "presentation"}
    %a.withoutripple{"aria-controls" => "settings", "data-toggle" => "tab", :href => "#groups", :role => "tab"}
      %i.fa.fa-group
      %span.hidden-xs Groups
      %span.badge.badge-round.badge-success 2
  %li{:role => "presentation"}
    %a.withoutripple{"aria-controls" => "settings", "data-toggle" => "tab", :href => "#questions", :role => "tab"}
      %i.fa.fa-question
      %span.hidden-xs Questions
  %li{:role => "presentation"}
    %a.withoutripple{"aria-controls" => "messages", "data-toggle" => "tab", :href => "#videos", :role => "tab"}
      %i.zmdi.zmdi-collection-video
      %span.hidden-xs Videos
  %li{:role => "presentation"}
    %a.withoutripple{"aria-controls" => "settings", "data-toggle" => "tab", :href => "#files", :role => "tab"}
      %i.fa.fa-file-pdf-o
      %span.hidden-xs Files

app/views/welcome/calendar.html.erb
<div class="ms-site-container ms-nav-fixed">
  <nav class="navbar navbar-expand-md navbar-fixed ms-lead-navbar navbar-mode navbar-mode mb-0" id="navbar-lead">
    <%= render 'shared/top_nav' %>
  </nav>
  <div class="wrap ms-hero-img-brain-color ms-hero-bg-info color-white ms-bg-fixed full-screen-height">
    <div class="container ms-paper-content index-1 mt-20">
      <div class="row">
        <div class="col-sm-12">
          <a class="btn btn-raised btn-primary pull-right" href="/voices">Finish</a>
        </div>
      </div>
      <section class="calendar-cover">
        <div id="calendar"></div>
      </section>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="ms-site-container">
  <!-- Modal -->
  <%= render 'shared/header'%>
  <nav class="navbar navbar-expand-md  navbar-static ms-navbar full-screen-heigh">
  <%= render 'shared/top_nav'%>
  </nav>
  <%= render 'shared/banner'%>
</div>

app/views/welcome/psychologists.html.erb
<div class="ms-site-container ms-nav-fixed">
  <nav class="navbar navbar-expand-md ms-lead-navbar navbar-mode navbar-mode mb-0" id="navbar-lead">
    <%= render 'shared/top_nav' %>
  </nav>
  <div class="wrap ms-hero-img-brain-color ms-hero-bg-info ms-bg-fixed full-screen-height">
    <div class="container ms-paper-content index-1">
      <section class="ms-component-section">
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="zmdi zmdi-graduation-cap"></i> Search Results</h3>
              </div>

              <div class="card-tabs">
                <ul class="nav nav-tabs nav-tabs-transparent indicator-primary nav-tabs-full nav-tabs-3" role="tablist">
                  <li class="nav-item">
                    <a href="#home3" aria-controls="home3" role="tab" data-toggle="tab" class="withoutripple nav-link ">
                      <i class="zmdi zmdi-accounts"></i>
                      <span class="d-none d-sm-inline">Groups</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#profile3" aria-controls="profile" role="tab" data-toggle="tab" class="withoutripple nav-link ">
                      <i class="zmdi zmdi-graduation-cap"></i>
                      <span class="d-none d-sm-inline">Mental Health Classroom</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#psychologits" aria-controls="psychologits" role="tab" data-toggle="tab" class="active withoutripple nav-link ">
                      <i class="zmdi zmdi-male"></i>
                      <span class="d-none d-sm-inline">Psychologists</span>
                    </a>
                  </li>
                </ul>
              </div>

              <div class="card-block">
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade" id="home3">
                    <%= render 'shared/groups/group' %>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="profile3">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse expedita ratione eum, praesentium
                      labore
                      nemo molestiae non, quasi similique enim natus. Maiores dolor architecto facilis cum cupiditate
                      aliquam
                      culpa natus!</p>
                    <p>Eos sapiente natus inventore quaerat, obcaecati explicabo delectus ipsa iste sit deserunt,
                      blanditiis
                      temporibus. Unde mollitia officiis eum. Ut autem voluptatibus maiores amet at magnam fuga
                      doloremque!
                      Explicabo, qui, eaque.</p>
                  </div>
                  <div role="tabpanel" class="tab-pane active fade show" id="psychologits">
                    <%= render 'shared/users/user' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>